version: "3.9"
services:
  blocks:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "4zbAFimpvtTo4LVDdD2fqFUOUW//v/Zu6qMOBx1PX0Q="
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=${DATABASE_URL}

